version: "3.7"
services:
  database:
    image: postgis/postgis:12-3.1
    ports:
      - 5432:5432
    volumes:
      - my_app-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - my_app-net

networks:
  my_app-net:
    driver: bridge

volumes:
  my_app-db-data:
    external: false
