version: "3.7"
services:
  database:
    image: postgis/postgis:12-3.1
    ports:
      - 5432:5432
    volumes:
      - boilerplate-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: boilerplate_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - boilerplate-net

networks:
  boilerplate-net:
    driver: bridge

volumes:
  boilerplate-db-data:
    external: false
